# Generated by Django 5.2.17 on 2026-10-06 22:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=110, unique=True)),
                (
                    "segment",
                    models.CharField(
                        choices=[
                            ("mass", "Mass manufacturing"),
                            ("custom", "Custom jobs"),
                            ("decor", "Home decor"),
                            ("medical", "Medical models"),
                        ],
                        default="decor",
                        max_length=10,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=250)),
                (
                    "icon",
                    models.CharField(
                        default="box",
                        help_text="Bootstrap icon name, e.g. lamp, gear, gift",
                        max_length=40,
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=10)),
            ],
            options={
                "verbose_name_plural": "categories",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("slug", models.SlugField(blank=True, max_length=170, unique=True)),
                (
                    "sku",
                    models.CharField(max_length=40, unique=True, verbose_name="SKU"),
                ),
                ("short_description", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "dimensions",
                    models.CharField(
                        blank=True, help_text="e.g. 12 x 12 x 20 cm", max_length=80
                    ),
                ),
                (
                    "vendor_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="What the vendor charges us per piece. The customer price adds our commission automatically.",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "price_override",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Optional: a rounded customer price (before GST) instead of the automatic one",
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "technology",
                    models.CharField(
                        choices=[
                            ("FDM", "FDM (filament)"),
                            ("SLA", "SLA (resin)"),
                            ("SLS", "SLS (nylon powder)"),
                            ("MJF", "MJF (multi jet fusion)"),
                        ],
                        default="FDM",
                        max_length=10,
                    ),
                ),
                (
                    "material",
                    models.CharField(
                        choices=[
                            ("PLA", "PLA"),
                            ("ABS", "ABS"),
                            ("PETG", "PETG"),
                            ("TPU", "TPU (flexible)"),
                            ("NYLON", "Nylon PA12"),
                            ("RESIN_STD", "Standard resin"),
                            ("RESIN_TOUGH", "Tough resin"),
                            ("OTHER", "Other / advise me"),
                        ],
                        default="PLA",
                        max_length=20,
                    ),
                ),
                (
                    "colours",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated, e.g. White, Black, Terracotta",
                        max_length=150,
                    ),
                ),
                ("lead_time_days", models.PositiveIntegerField(default=5)),
                ("min_quantity", models.PositiveIntegerField(default=1)),
                (
                    "hsn_code",
                    models.CharField(
                        blank=True,
                        help_text="Printed on the tax invoice",
                        max_length=8,
                        verbose_name="HSN code",
                    ),
                ),
                ("image", models.BinaryField(blank=True, null=True)),
                (
                    "image_type",
                    models.CharField(blank=True, editable=False, max_length=40),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Published"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="catalog.category",
                    ),
                ),
            ],
            options={
                "ordering": ["category__sort_order", "name"],
            },
        ),
    ]
