# Generated by Django 5.2.17 on 2026-10-06 22:46

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InvoiceSequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("financial_year", models.CharField(max_length=7, unique=True)),
                ("last_number", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        blank=True, editable=False, max_length=20, unique=True
                    ),
                ),
                (
                    "order_type",
                    models.CharField(
                        choices=[
                            ("catalog", "Catalogue order"),
                            ("custom", "Custom request"),
                        ],
                        default="custom",
                        max_length=10,
                    ),
                ),
                (
                    "segment",
                    models.CharField(
                        choices=[
                            ("mass", "Mass manufacturing"),
                            ("custom", "Custom jobs"),
                            ("decor", "Home decor"),
                            ("medical", "Medical models"),
                        ],
                        default="custom",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Request received"),
                            ("pricing", "Being priced"),
                            ("quoted", "Quote sent"),
                            ("awaiting_payment", "Awaiting payment"),
                            ("confirmed", "Confirmed"),
                            ("in_production", "In production"),
                            ("ready", "Packed, ready to ship"),
                            ("shipped", "Shipped"),
                            ("delivered", "Delivered"),
                            ("cancelled", "Cancelled"),
                            ("rejected", "Not accepted"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=20,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=150, verbose_name="Project / item name"
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "technology",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("FDM", "FDM (filament)"),
                            ("SLA", "SLA (resin)"),
                            ("SLS", "SLS (nylon powder)"),
                            ("MJF", "MJF (multi jet fusion)"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "material",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PLA", "PLA"),
                            ("ABS", "ABS"),
                            ("PETG", "PETG"),
                            ("TPU", "TPU (flexible)"),
                            ("NYLON", "Nylon PA12"),
                            ("RESIN_STD", "Standard resin"),
                            ("RESIN_TOUGH", "Tough resin"),
                            ("OTHER", "Other / advise me"),
                        ],
                        max_length=20,
                    ),
                ),
                ("colour", models.CharField(blank=True, max_length=40)),
                (
                    "finish",
                    models.CharField(
                        choices=[
                            ("raw", "As printed"),
                            ("sanded", "Sanded / smoothed"),
                            ("primed", "Primed"),
                            ("painted", "Painted"),
                        ],
                        default="raw",
                        max_length=10,
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("required_by", models.DateField(blank=True, null=True)),
                (
                    "file_link",
                    models.URLField(
                        blank=True,
                        help_text="Google Drive, Dropbox or WeTransfer link for files above the upload limit",
                        verbose_name="Link to large files",
                    ),
                ),
                (
                    "vendor_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Vendor's total price for this order, including delivery",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "vendor_lead_days",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("vendor_note", models.CharField(blank=True, max_length=500)),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Price before GST",
                    ),
                ),
                (
                    "gst_percent",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("18"), max_digits=5
                    ),
                ),
                ("quote_note", models.CharField(blank=True, max_length=500)),
                ("quoted_at", models.DateTimeField(blank=True, null=True)),
                ("quote_valid_until", models.DateField(blank=True, null=True)),
                (
                    "ship_name",
                    models.CharField(max_length=120, verbose_name="Recipient name"),
                ),
                (
                    "ship_phone",
                    models.CharField(max_length=20, verbose_name="Recipient phone"),
                ),
                ("ship_address", models.TextField(verbose_name="Delivery address")),
                ("ship_city", models.CharField(max_length=80, verbose_name="City")),
                (
                    "ship_state",
                    models.CharField(
                        choices=[
                            (
                                "Andaman and Nicobar Islands",
                                "Andaman and Nicobar Islands",
                            ),
                            ("Andhra Pradesh", "Andhra Pradesh"),
                            ("Arunachal Pradesh", "Arunachal Pradesh"),
                            ("Assam", "Assam"),
                            ("Bihar", "Bihar"),
                            ("Chandigarh", "Chandigarh"),
                            ("Chhattisgarh", "Chhattisgarh"),
                            (
                                "Dadra and Nagar Haveli and Daman and Diu",
                                "Dadra and Nagar Haveli and Daman and Diu",
                            ),
                            ("Delhi", "Delhi"),
                            ("Goa", "Goa"),
                            ("Gujarat", "Gujarat"),
                            ("Haryana", "Haryana"),
                            ("Himachal Pradesh", "Himachal Pradesh"),
                            ("Jammu and Kashmir", "Jammu and Kashmir"),
                            ("Jharkhand", "Jharkhand"),
                            ("Karnataka", "Karnataka"),
                            ("Kerala", "Kerala"),
                            ("Ladakh", "Ladakh"),
                            ("Lakshadweep", "Lakshadweep"),
                            ("Madhya Pradesh", "Madhya Pradesh"),
                            ("Maharashtra", "Maharashtra"),
                            ("Manipur", "Manipur"),
                            ("Meghalaya", "Meghalaya"),
                            ("Mizoram", "Mizoram"),
                            ("Nagaland", "Nagaland"),
                            ("Odisha", "Odisha"),
                            ("Puducherry", "Puducherry"),
                            ("Punjab", "Punjab"),
                            ("Rajasthan", "Rajasthan"),
                            ("Sikkim", "Sikkim"),
                            ("Tamil Nadu", "Tamil Nadu"),
                            ("Telangana", "Telangana"),
                            ("Tripura", "Tripura"),
                            ("Uttar Pradesh", "Uttar Pradesh"),
                            ("Uttarakhand", "Uttarakhand"),
                            ("West Bengal", "West Bengal"),
                        ],
                        max_length=60,
                        verbose_name="State",
                    ),
                ),
                (
                    "ship_pincode",
                    models.CharField(max_length=6, verbose_name="PIN code"),
                ),
                (
                    "bill_company",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        verbose_name="Company name on invoice",
                    ),
                ),
                (
                    "bill_gstin",
                    models.CharField(
                        blank=True, max_length=15, verbose_name="Your GSTIN"
                    ),
                ),
                ("courier", models.CharField(blank=True, max_length=60)),
                (
                    "tracking_number",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="AWB / tracking number"
                    ),
                ),
                ("tracking_url", models.URLField(blank=True)),
                ("shipped_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("invoice_number", models.CharField(blank=True, max_length=30)),
                ("invoice_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="jobs",
                        to="accounts.vendorprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("customer", "With customer"),
                            ("vendor", "With vendor"),
                            ("internal", "Internal note"),
                        ],
                        default="customer",
                        max_length=10,
                    ),
                ),
                ("body", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("size", models.PositiveBigIntegerField(default=0)),
                ("content_type", models.CharField(blank=True, max_length=100)),
                ("data", models.BinaryField()),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("model", "3D model"),
                            ("drawing", "Drawing / reference"),
                            ("qc_photo", "Quality-check photo"),
                            ("other", "Other"),
                        ],
                        default="model",
                        max_length=10,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="orders.order",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "unit_vendor_price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("colour", models.CharField(blank=True, max_length=40)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalog.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("upi", "UPI"),
                            ("neft", "NEFT / RTGS / IMPS"),
                            ("cheque", "Cheque"),
                            ("other", "Other"),
                        ],
                        default="upi",
                        max_length=10,
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        max_length=60, verbose_name="UTR / reference number"
                    ),
                ),
                ("paid_on", models.DateField()),
                ("proof", models.BinaryField(blank=True, null=True)),
                ("proof_name", models.CharField(blank=True, max_length=255)),
                ("proof_type", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Waiting for approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=300)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="orders.order",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StatusEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_status", models.CharField(blank=True, max_length=20)),
                ("to_status", models.CharField(max_length=20)),
                ("note", models.CharField(blank=True, max_length=500)),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            ("all", "Customer and vendor"),
                            ("customer", "Customer and staff"),
                            ("vendor", "Vendor and staff"),
                            ("staff", "Staff only"),
                        ],
                        default="all",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="VendorPayout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "period",
                    models.DateField(
                        help_text="First day of the month this payment settles"
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "reference",
                    models.CharField(max_length=60, verbose_name="UTR / reference"),
                ),
                ("paid_on", models.DateField()),
                ("vendor_invoice_number", models.CharField(blank=True, max_length=40)),
                ("note", models.CharField(blank=True, max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recorded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payouts",
                        to="accounts.vendorprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-period", "-paid_on"],
            },
        ),
    ]
